#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

# This wizard never persists inputs to .env. Credentials only exist in memory
# long enough to be passed to Wrangler's secret command through standard input.
ENV_FILE=/dev/null

if [[ "${1:-}" == "--help" ]]; then
  printf '%s\n' 'Usage: npm run setup:bitkub-account'
  printf '%s\n' 'Creates a non-secret Bitkub account row in remote D1, then updates the Sync Worker credential map.'
  exit 0
fi

die() {
  warn "$1"
  exit 1
}

sql_literal() {
  printf '%s' "$1" | sed "s/'/''/g; s/^/'/; s/\$/'/"
}

run_wrangler() {
  npm exec -- wrangler "$@"
}

validate_account_inputs() {
  [[ "$ACCOUNT_ID" =~ ^[A-Za-z0-9_-]{1,64}$ ]] || die 'Account ID must use 1–64 letters, numbers, hyphens, or underscores.'
  [[ -n "$ACCOUNT_LABEL" && ${#ACCOUNT_LABEL} -le 80 ]] || die 'Account label must be 1–80 characters.'
  [[ "$OWNER_EMAIL" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]] || die 'Enter a valid owner email address.'
  [[ -n "$DATABASE_NAME" ]] || die 'A D1 database name is required.'
  [[ -f "$CONFIG_PATH" ]] || die "Wrangler config not found: $CONFIG_PATH"
}

validate_credential_map() {
  printf '%s' "$BITKUB_ACCOUNTS_JSON" | node -e '
    const fs = require("node:fs");
    const accountId = process.argv[1];
    const queryResponse = JSON.parse(process.argv[2]);
    const groups = Array.isArray(queryResponse) ? queryResponse : [queryResponse];
    const expected = groups.flatMap((group) => Array.isArray(group.results) ? group.results : [])
      .map((row) => row.id).filter((id) => typeof id === "string");
    const value = JSON.parse(fs.readFileSync(0, "utf8"));
    const isCredential = (entry) => entry && typeof entry === "object" && !Array.isArray(entry)
      && typeof entry.apiKey === "string" && entry.apiKey.length > 0
      && typeof entry.apiSecret === "string" && entry.apiSecret.length > 0;
    if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Expected a JSON object.");
    const keys = Object.keys(value);
    if (!expected.includes(accountId) || keys.length !== expected.length
      || expected.some((id) => !isCredential(value[id])) || keys.some((id) => !expected.includes(id))) {
      throw new Error("The map must contain exactly one non-empty read-only credential pair for every Bitkub account in D1.");
    }
  ' "$ACCOUNT_ID" "$ACCOUNT_ROWS_JSON"
}

list_bitkub_account_ids() {
  printf '%s' "$1" | node -e '
    const fs = require("node:fs");
    const response = JSON.parse(fs.readFileSync(0, "utf8"));
    const groups = Array.isArray(response) ? response : [response];
    const ids = groups.flatMap((group) => Array.isArray(group.results) ? group.results : [])
      .map((row) => row.id).filter((id) => typeof id === "string");
    if (ids.length === 0) throw new Error("No Bitkub account IDs were returned from D1.");
    process.stdout.write(ids.join(", "));
  '
}

banner "Add a Bitkub account"

stage "Account identity"
say "Create a separate Bitkub key first in your signed-in Bitkub account. It must have read access only: no trade and no withdrawal permission."
step "Enter a new local account ID. It is not a Bitkub ID and will become the exact key in the secret map."
ask ACCOUNT_ID "Local account ID (for example bitkub-secondary):"
ask ACCOUNT_LABEL "Dashboard label (for example Bitkub Secondary):"
ask OWNER_EMAIL "Owner email (for display only):"
ask DATABASE_NAME "Remote D1 database name:"
ask CONFIG_OVERRIDE "Wrangler config path [Enter for apps/sync-worker/wrangler.jsonc]:"
CONFIG_PATH="${CONFIG_OVERRIDE:-apps/sync-worker/wrangler.jsonc}"
validate_account_inputs
note "The browser and D1 will never receive the Bitkub API key or secret."
pause "Account details are ready. Press Enter to create the D1 row."

stage "Create the account row"
say "This writes one non-secret account record to your remote D1 database."
warn "Until the next stage completes, the new account safely remains unsynced; legacy single-account keys are intentionally refused once two accounts exist."
confirm "Create Bitkub account '$ACCOUNT_ID' in remote D1" || die 'Cancelled before changing D1.'
ACCOUNT_SQL="INSERT INTO accounts (id, exchange, label, owner_email, created_at) VALUES ($(sql_literal "$ACCOUNT_ID"), 'bitkub', $(sql_literal "$ACCOUNT_LABEL"), $(sql_literal "$OWNER_EMAIL"), CAST(strftime('%s', 'now') AS INTEGER) * 1000);"
run_wrangler d1 execute "$DATABASE_NAME" --remote --config "$CONFIG_PATH" --command "$ACCOUNT_SQL"
say "Account row created. Reading the complete Bitkub account-ID list for secret-map validation."
ACCOUNT_ROWS_JSON=$(run_wrangler d1 execute "$DATABASE_NAME" --remote --config "$CONFIG_PATH" --command "SELECT id FROM accounts WHERE exchange = 'bitkub' AND archived_at IS NULL ORDER BY id;" --json)
ACCOUNT_IDS=$(list_bitkub_account_ids "$ACCOUNT_ROWS_JSON") || die 'Could not read the Bitkub account IDs returned by D1.'
say "The credential map must contain exactly these Bitkub account IDs: $ACCOUNT_IDS"
pause "Review the IDs above, then press Enter to continue."

stage "Set the credential map"
say "Paste one compact JSON object containing every Bitkub account ID and its separate read-only credential pair."
say "It is hidden while you paste, never written to .env/D1, and sent only to Cloudflare's Wrangler secret command."
warn "This replaces BITKUB_ACCOUNTS_JSON. Omitting an existing account would stop its sync, so validation rejects incomplete or extra map entries."
ask_secret BITKUB_ACCOUNTS_JSON "Paste the complete credential map:"
[[ -n "$BITKUB_ACCOUNTS_JSON" ]] || die 'Credential map cannot be empty.'
validate_credential_map || die 'Credential map validation failed; D1 was not changed further and no secret was set.'
confirm "Set BITKUB_ACCOUNTS_JSON on the Sync Worker" || die 'Cancelled before setting the Cloudflare secret.'
printf '%s' "$BITKUB_ACCOUNTS_JSON" | run_wrangler secret put BITKUB_ACCOUNTS_JSON --config "$CONFIG_PATH"
unset BITKUB_ACCOUNTS_JSON
say "The secret map was set. The next scheduled or manual read-only sync will populate this account."
finish
