#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: first self-hosted installation. This is intentionally local-only.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

if [[ "${1:-}" == "--help" ]]; then
  printf '%s\n' 'Usage: npm run setup'
  printf '%s\n' 'Creates a new, independent Cloudflare installation of Moondi.'
  printf '%s\n' 'It writes only ignored local configuration and sends Bitkub credentials directly to Wrangler prompts.'
  exit 0
fi

die() {
  warn "$1"
  exit 1
}

run_wrangler() {
  npm exec -- wrangler "$@"
}

validate_slug() {
  [[ "$1" =~ ^[a-z0-9]([a-z0-9-]{0,40}[a-z0-9])?$ ]] || die 'Use 1–42 lowercase letters, numbers, and hyphens; begin and end with a letter or number.'
}

validate_email() {
  [[ "$1" =~ ^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$ ]] || die 'Enter a valid owner email address.'
}

validate_d1_id() {
  [[ "$1" =~ ^[[:xdigit:]]{8}-[[:xdigit:]]{4}-[[:xdigit:]]{4}-[[:xdigit:]]{4}-[[:xdigit:]]{12}$ ]] || die 'The D1 database ID must be the UUID shown by Wrangler.'
}

validate_kv_id() {
  [[ "$1" =~ ^[[:xdigit:]]{32}$ ]] || die 'The KV namespace ID must be the 32-character hexadecimal ID shown by Wrangler.'
}

validate_origin() {
  [[ "$1" =~ ^https://[A-Za-z0-9.-]+$ ]] || die 'Enter only an HTTPS origin, for example https://my-api.example.workers.dev (no path or trailing slash).'
}

sql_literal() {
  printf '%s' "$1" | sed "s/'/''/g; s/^/'/; s/\$/'/"
}

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$REPO_ROOT"

[[ -f package.json && -f apps/api/wrangler.example.jsonc && -f apps/sync-worker/wrangler.example.jsonc ]] || die 'Run this command from an unmodified Moondi repository.'
[[ ! -e apps/api/wrangler.jsonc && ! -e apps/sync-worker/wrangler.jsonc && ! -e apps/web/.env ]] || die 'Local installation config already exists. This wizard refuses to overwrite it; use the deployment guide for an existing installation.'
command -v node >/dev/null 2>&1 || die 'Node.js is required.'
command -v npm >/dev/null 2>&1 || die 'npm is required.'

banner "Moondi self-hosted setup"

stage "Check your Cloudflare account"
say "This installer creates resources only in the Cloudflare account authenticated in Wrangler. It never contacts a Moondi service."
if ! run_wrangler whoami --json >/dev/null; then
  warn 'Wrangler is not authenticated.'
  step 'Run: npx wrangler login'
  die 'Sign in to your own Cloudflare account, then run npm run setup again.'
fi
say "Wrangler authentication is ready."
pause "Press Enter to choose names for this independent installation."

stage "Name your installation"
say "These names become your D1 database, KV namespace, Workers, and Pages project. They must be unique within your Cloudflare account."
ask INSTALL_SLUG "Installation name (for example my-moondi):"
validate_slug "$INSTALL_SLUG"
ask OWNER_EMAIL "Owner email for the first Bitkub account:"
validate_email "$OWNER_EMAIL"
ask D1_LOCATION "D1 location [Enter for apac; weur, eeur, oc, wnam, enam]:"
D1_LOCATION="${D1_LOCATION:-apac}"
[[ "$D1_LOCATION" =~ ^(apac|weur|eeur|oc|wnam|enam)$ ]] || die 'Choose one of: apac, weur, eeur, oc, wnam, enam.'

DATABASE_NAME="${INSTALL_SLUG}-db"
KV_NAMESPACE_NAME="${INSTALL_SLUG}-cache"
API_WORKER_NAME="${INSTALL_SLUG}-api"
SYNC_WORKER_NAME="${INSTALL_SLUG}-sync"
PAGES_PROJECT_NAME="$INSTALL_SLUG"
PAGES_ORIGIN="https://${PAGES_PROJECT_NAME}.pages.dev"

say "D1: $DATABASE_NAME · KV: $KV_NAMESPACE_NAME · API: $API_WORKER_NAME · Sync: $SYNC_WORKER_NAME · Pages: $PAGES_PROJECT_NAME"
warn 'Creating D1 and KV creates resources in your Cloudflare account. The installer will not delete resources automatically if you cancel later.'
confirm "Create these Cloudflare resources" || die 'Cancelled before creating Cloudflare resources.'

stage "Create D1 and KV"
say "Wrangler will print each resource ID. Copy each ID from the output when asked; IDs are configuration data, not passwords."
run_wrangler d1 create "$DATABASE_NAME" --location "$D1_LOCATION"
ask DATABASE_ID "Paste the D1 database ID Wrangler printed:"
validate_d1_id "$DATABASE_ID"
run_wrangler kv namespace create "$KV_NAMESPACE_NAME"
ask KV_NAMESPACE_ID "Paste the KV namespace ID Wrangler printed:"
validate_kv_id "$KV_NAMESPACE_ID"

stage "Write local configuration"
say "The installer writes your own ignored wrangler.jsonc files. They contain resource IDs and are never added to Git."
node scripts/write-install-config.mjs \
  --dbId "$DATABASE_ID" \
  --dbName "$DATABASE_NAME" \
  --pagesOrigin "$PAGES_ORIGIN" \
  --apiWorkerName "$API_WORKER_NAME" \
  --syncWorkerName "$SYNC_WORKER_NAME" \
  --kvId "$KV_NAMESPACE_ID"
npm run types --workspace @moondi/api
npm run types --workspace @moondi/sync-worker
say "Local Worker configuration and generated binding types created."

stage "Initialize data and account"
say "This applies the committed migrations to your new D1 database, then adds one non-secret Bitkub account row."
confirm "Apply all Moondi migrations to $DATABASE_NAME" || die 'Cancelled before database migration.'
run_wrangler d1 migrations apply "$DATABASE_NAME" --remote --config apps/api/wrangler.jsonc
ask ACCOUNT_ID "First local Bitkub account ID [Enter for bitkub-main]:"
ACCOUNT_ID="${ACCOUNT_ID:-bitkub-main}"
[[ "$ACCOUNT_ID" =~ ^[A-Za-z0-9_-]{1,64}$ ]] || die 'Account ID must use 1–64 letters, numbers, hyphens, or underscores.'
ask ACCOUNT_LABEL "First account label [Enter for Bitkub Main]:"
ACCOUNT_LABEL="${ACCOUNT_LABEL:-Bitkub Main}"
[[ -n "$ACCOUNT_LABEL" && ${#ACCOUNT_LABEL} -le 80 ]] || die 'Account label must be 1–80 characters.'
ACCOUNT_SQL="INSERT INTO accounts (id, exchange, label, owner_email, created_at) VALUES ($(sql_literal "$ACCOUNT_ID"), 'bitkub', $(sql_literal "$ACCOUNT_LABEL"), $(sql_literal "$OWNER_EMAIL"), CAST(strftime('%s', 'now') AS INTEGER) * 1000);"
confirm "Create the non-secret account row '$ACCOUNT_ID'" || die 'Cancelled before adding the account row.'
run_wrangler d1 execute "$DATABASE_NAME" --remote --config apps/api/wrangler.jsonc --command "$ACCOUNT_SQL"

stage "Deploy the read-only Workers"
say "The sync Worker is deployed first, then the API Worker binds to it internally. No exchange credential has been set yet."
npm run deploy --workspace @moondi/sync-worker
npm run deploy --workspace @moondi/api
say "Copy the API Worker HTTPS URL printed by the second deployment; you will paste it in the next stage."

stage "Set the Bitkub read-only credentials"
warn 'Use a dedicated Bitkub API key with read access only. Never enable trade or withdrawal permissions.'
say "Wrangler will now prompt for the key and secret directly. They are not written to this script, configuration files, Git, or the browser."
pause "Press Enter to set BITKUB_API_KEY."
run_wrangler secret put BITKUB_API_KEY --config apps/sync-worker/wrangler.jsonc
pause "Press Enter to set BITKUB_API_SECRET."
run_wrangler secret put BITKUB_API_SECRET --config apps/sync-worker/wrangler.jsonc
say "The Bitkub credentials are stored only as Cloudflare Worker secrets."

stage "Deploy the private dashboard"
ask API_ORIGIN "Paste the API Worker HTTPS origin printed earlier:"
validate_origin "$API_ORIGIN"
ENV_FILE=apps/web/.env
write_env VITE_API_BASE_URL "$API_ORIGIN"
npm run build --workspace @moondi/web
run_wrangler pages deploy apps/web/dist --project-name "$PAGES_PROJECT_NAME"
say "Pages deployment is complete at $PAGES_ORIGIN."
if command -v curl >/dev/null 2>&1; then
  if curl --fail --silent --show-error "$API_ORIGIN/health" >/dev/null; then
    say "API health check succeeded."
  else
    warn 'The API health check did not succeed yet. Check the pasted API origin and Worker deployment before adding Access.'
  fi
fi

stage "Protect and verify"
say "Cloudflare Access is intentionally a manual final step: it determines who may see financial data."
open_url "https://one.dash.cloudflare.com/"
step "Create Access applications for the Pages origin and API origin. Use Google and an explicit email allow-list; do not allow every Google account."
step "Open $PAGES_ORIGIN, sign in through Access, then check Sync health after the scheduled read-only sync."
note "The first price chart appears after enough recorded snapshots. Browser push and manual sync are optional follow-up features; see docs/quickstart.md."
pause "Press Enter after recording the Access checklist."

finish
